### ISSUE TITLE
Boost original Toot instead of [RT] when OP is on birdsite.live

### ISSUE THREAD

**Issue by tofuwabohu** [NicolasConstant/BirdsiteLive#101]
Currently, Retweets are posted with [RT @OriginalPoster], linking to the Twitter link and birdsite.live profile, which just will be generated if not existent.

I'd suggest birdsite.love does the following:
Check if the OP of the retweeted tweet is active on birdsite.live, and if yes, boost their post instead
If not, there would be 2 possibilities:

1. Do it like it currently is
2. Create the profile on birdsite.love, crosspost the tweet in question, then boost it

I think in both cases, things would get complicated, if a Twitter profile is mirrored on different BirdsiteLive instances or is already mirrored at one page and then the current page creates another mirror. But that may be a general problem of BirdsiteLive with different instances I guess?

**Comment by tofuwabohu** [comment]
I just realized the crossposts are private per default so that's not possible probably.

**Comment by NicolasConstant** [comment]
Yes the current limitation is unfortunately linked to the follower-only mode, I would love boosting those tweets on follower-only mode but it's not available in current common ActivityPub implementations. 😕
