### ISSUE TITLE
[Feature Request] Admin CLI

### ISSUE THREAD

**Issue by garritfra** [NicolasConstant/BirdsiteLive#104]
Hi! My [instance](https://birdsite.slashdev.space) is currently overflowing due to many users. What I'd like to have is some sort of Admin CLI that allows me to see who is following whom so that I can act on them accordingly.

**Comment by garritfra** [comment]
I used this SQL-query as a workaround:
```sql
SELECT id, followings, acct, host FROM followers;
```

**Comment by NicolasConstant** [comment]
I'm already working on something equivalent but didn't found the time to release it already... it should come out soon!

**Comment by NicolasConstant** [comment]
Available in 0.17.0 🙂
See [the doc](https://github.com/NicolasConstant/BirdsiteLive/blob/master/BSLManager.md) for more information.
