### ISSUE TITLE
CW all tweets from account

### ISSUE THREAD

**Issue by nytpu** [NicolasConstant/BirdsiteLive#110]
There are a few accounts I'm following that consistently post NSFW content which isn't CWed/marked as sensitive, as the entire account is marked as 18+ on twitter.

It'd be nice if there was a way to automatically CW all tweets from an account with some generic message, with the accounts configurable through something similar to the `Instance:UnlistedTwitterAccounts` variable or somehow detecting it by checking if the account is marked as 18+ on twitter.

**Comment by nytpu** [comment]
I'm not super familiar with C# but if you could point me in the right direction for how I'd start on this I could take a crack at it.

**Comment by NicolasConstant** [comment]
Sure, that would be a nice feature! 
For the settings part, you can test locally very easily with a 1:1 ratio with the docker environment variables and the [config file](https://github.com/NicolasConstant/BirdsiteLive/blob/master/src/BirdsiteLive/appsettings.json) (rename it `appsettings.development.json` to load it in debug).

The part where those settings are loaded and registered in the DI container is [here](https://github.com/NicolasConstant/BirdsiteLive/blob/master/src/BirdsiteLive/Startup.cs#L61).

And the part where I currently unlist some accounts [is here](https://github.com/NicolasConstant/BirdsiteLive/blob/07dc912624bb0d7fcab5f6bf134bde6b2143a2b0/src/BirdsiteLive.Domain/StatusService.cs#L48) (I believe you'd like to be close to this other functionality).

I also have a [Discord](https://discord.gg/8NXk9c6eXv) if you want to exchange more dynamically / get some help. 🙂
