### ISSUE TITLE
Private-use BirdsiteLIVE instances

### ISSUE THREAD

**Issue by robflop** [NicolasConstant/BirdsiteLive#121]
Hey Nicolas,

could you make it possible to make an instance of BirdsiteLIVE private, meaning that only the owner of the instance can modify the list of accounts that are being mirrored by this instance? From what I see, this is currently not possible

If I was to set up an instance to follow accounts from Twitter that I like, I wouldn't want other users that I don't know to make my instance mirror accounts that I don't want it to (e.g. I don't want my instance to mirror political figures of any kind or the like).

It'd also be relevant for things like saturation and server bandwidth - i'd prefer keeping my instance satured with only the accounts that I actually follow, and not have it be filled up by those that are not relevant to me.

**Comment by NicolasConstant** [comment]
Hi! 
You can whitelist your own ActivityPub Account (Mastodon, Pleroma, etc) and it should provide the behavior you're describing: only your account will be able to follow and mirror anything from your instance. 
https://github.com/NicolasConstant/BirdsiteLive/blob/master/VARIABLES.md
Please tell me if your use case is a bit more subtle than that.

**Comment by robflop** [comment]
Oh, I actually read that file but must've somehow either misunderstood the purpose or mentally skipped over that.
This seems to be what i'm looking for, yea. I'll give it a shot once I can and then let you know if the issue is solved.
