### ISSUE TITLE
Unable to follow any users

### ISSUE THREAD

**Issue by CaramelKat** [NicolasConstant/BirdsiteLive#125]
I apologize if I'm just missing something obvious here, but I'm having issues following any users on my instance. When clicking follow, instead of going through I get a pending follow request instead. As a result, it's not pulling any tweets. 

I initially believed it was an issue with the config file, but after trying the default, blacklist, and whitelist for mastodon instances I'm not so sure anymore. I've been able to reproduce this in both 0.18.0 and the current edge build (0.19.0) on docker. I've embedded my `docker-compose.yml` file below in case I've missed something. I've also attached what I'm seeing in the docker container logs after following if that helps.

```
version: "3"

networks:
    birdsitelivenetwork:
        external: false

services:
    server:
        image: nicolasconstant/birdsitelive:edge
        restart: always
        container_name: birdsitelive
        environment:
            - Instance:Domain=[domain]
            - Instance:AdminEmail=[email]
            - Db:Type=postgres
            - Db:Host=db
            - Db:Name=birdsitelive
            - Db:User=birdsitelive
            - Db:Password=birdsitelive
            - Twitter:ConsumerKey=[key]
            - Twitter:ConsumerSecret=[secret]
            - Instance:Name=BirdsiteLive
            - Instance:ResolveMentionsInProfiles=true
            - Instance:PublishReplies=true
        networks:
            - birdsitelivenetwork
        ports:
            - "5000:80"
        depends_on:
            - db

    db:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=birdsitelive
            - POSTGRES_PASSWORD=[password]
            - POSTGRES_DB=birdsitelive
        networks:
            - birdsitelivenetwork
        volumes:
            - ./postgres:/var/lib/postgresql/data
```
```
info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET https://mastodon.jemverse.xyz/users/Jemma
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET https://mastodon.jemverse.xyz/users/Jemma
info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 39.1407ms - 200
info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 39.6791ms - 200
info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET https://mastodon.jemverse.xyz/users/Jemma
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET https://mastodon.jemverse.xyz/users/Jemma
info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 20.3114ms - 200
info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 20.6947ms - 200
```

**Comment by NicolasConstant** [comment]
Hi! 
It's not you nor your installation, it seems I have currently an issue with the authentication aspect with the last versions of Mastodon. I'll try to find some time in the following days to find what's going on.

**Comment by NicolasConstant** [comment]
Having a second look to your docker-config I just want to make sure: 

`- Db:Password=birdsitelive`
`- POSTGRES_PASSWORD=[password]`

those two must be the same, are they set the same way in your file?

**Comment by CaramelKat** [comment]
Yes they are the same in my file, I honestly don't remember why I thought to censor it lol.
Glad to know it wasn't just me with the issues though

**Comment by NicolasConstant** [comment]
I've have done some tests on my side (I had some reports of BSL failing to work properly but for now it seems all is working normally). 

Can you test the following? 
- make sure your last docker-compose modifications are deployed, to do so just run again `docker-compose up -d`
- can you also try to follow a very active account on the official instance to check if it's your deployment or the software that seems to have issues (news media like `@afp@beta.birdsite.live` is great for those kind of validation)

**Comment by CaramelKat** [comment]
Redeployed the docker instance, still using the edge version, same config as above (with the POSTGRES_PASSWORD set to birdsitelive ofc). I can follow `@afp@beta.birdsite.liv` just fine, but `@afp@birdsite.jemverse.xyz) still goes to `Cancel follow request`

**Comment by NicolasConstant** [comment]
I've heard some nginx issues could lead to some issues of this kind, are your using nginx as reverse proxy with this [kind of configuration](https://github.com/NicolasConstant/BirdsiteLive/blob/master/INSTALLATION.md#create-nginx-configuration) or is it a different deployment?

**Comment by CaramelKat** [comment]
I am using nginx as a reverse proxy, looking at the sample config, I forgot to add `proxy_cache_bypass $http_upgrade;` and that seems to have solved the following issue at least, I've just followed one of my accounts and tweeted after, so I presume as long as I see that tweet in my feed in the next 15ish minutes we should be good to go!

**Comment by NicolasConstant** [comment]
Great! Maybe you'll need to tweet again in 15 mins to make sure the system had the chance to do the initialization before synchronizing.

**Comment by CaramelKat** [comment]
Just wanted to give one last update, it's all working! So it really was that config issue with nginx. My bad! Glad to know it's not a real bug lol. Thanks for the help!

**Comment by NicolasConstant** [comment]
That's great and you're welcome! 🙂
