### ISSUE TITLE
Purge failing followers/instances

### ISSUE THREAD

**Issue by nielspeen** [NicolasConstant/BirdsiteLive#128]
Is there a way to automatically purge (followers on) instances that are down for a longer period (likely just gone for good)?

When a follower reaches 32767 posting failures this starts to cause postgres errors as a smallint is used for this field. I currently remove such followers using the BSL Manager, but I would prefer it to be automatic.

**Comment by NicolasConstant** [comment]
Yes I have to enhance all this, with BSLManager itself that isn't great the way it's done right now, and also provide some options for auto-cleaning in the settings. 

Thanks for contributing to BSL!

**Comment by NicolasConstant** [comment]
fixed in 0.20.0!
