### ISSUE TITLE
Replace the colon in environment variables with underscore

### ISSUE THREAD

**Issue by suda** [NicolasConstant/BirdsiteLive#136]
I noticed that DigitalOcean doesn't like the colons in the env variable names:
![Screenshot from 2022-02-08 15-37-23](https://user-images.githubusercontent.com/25722/153008907-be249617-d03a-4597-ac91-09b4aa6f41c2.png)

Would it be possible to replace them with underscores to look like `TWITTER_CONSUMER_KEY`?

**Comment by NicolasConstant** [comment]
Hi! 
This is something handled directly by the framework I use, but the good news is that you can replace the colon `:` separator with the double underscore `__` one (cf [the documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration&view=aspnetcore-3.1#environment-variables) if you need more insights).
