### ISSUE TITLE
Follow requests stuck in "awaiting approval"

### ISSUE THREAD

**Issue by srwalter** [NicolasConstant/BirdsiteLive#140]
I am trying to set up my own instance of birdsite.  It is mostly working, I can access my instance via HTTPS and search for Twitter users.  I can also search and find these users from a Mastodon server (fosstodon.org).  However, when I try to follow one, it goes into an "Awaiting approval" state, and I can't find any way in BirdsiteLive to approve these.  What am I missing?

**Comment by NicolasConstant** [comment]
Hi! 
Maybe there is some SSL issues, can you check your instance is having a good rating via this website? 
https://www.ssllabs.com/ssltest/

**Comment by NicolasConstant** [comment]
Is your issue solved?
