### ISSUE TITLE
[Issue] Npgsql.PostgresException - password authentication failed for user

### ISSUE THREAD

**Issue by Goelant** [NicolasConstant/BirdsiteLive#146]
Hey !
First of all : what a great tool you made, thanks a lot !

I just had a little issue while creating my instance. I was trying to change all passwords from the database area, looking to not make any miss-match between up and down section.

Once done, I ran the docker compose command but when I tried to run the website, it gave me a 500 : With docker logs <instance> I found the error code of this issue's title.

I then recovered the default DB name, username and password and it worked. I added this same single letter to both of them, composed and got the 500 back.

Maybe i made a mistake on how to edit postgre's password ?

Here is my .yml file, and as you can see, Name, Password and User strings are the same
![image](https://user-images.githubusercontent.com/101263819/165190959-0dc2d99a-1d17-4635-b254-81355881dec7.png)

Here is my failing request with custom credentials : 
![image](https://user-images.githubusercontent.com/101263819/165191124-587b30ef-04ef-4844-8c2e-de35029e9411.png)

And finaly logs from docker : 
![image](https://user-images.githubusercontent.com/101263819/165191206-0faa100c-ee91-45bb-96c3-fc58b891f3d4.png)
![image](https://user-images.githubusercontent.com/101263819/165191239-81221e24-6662-4a50-a09c-09a8fef4c8b8.png)

I'm pretty sure that I'm doing a bad mistake but well, if I can then help other peoples doing mistakes by filling an issue i'm doing it xD !

**Comment by NicolasConstant** [comment]
If you started-up the instance with defaults credentials before changing them, then your postgres DB is already created and will not be changed/recreated after that.

To reset the DB, just remove the `./postgres` folder and relaunch the instance with the proper credentials you want to use. It should work after that. 🙂

**Comment by Goelant** [comment]
I tried to do that but it seems I can't get it to work even by deleting ./postgres ... I maybe have somehwere a problem with docker ... I'll keep you up

**Comment by NicolasConstant** [comment]
Please try this;
* unload all with `docker-compose down`
* delete the postgres folder `rm -rf ./postgres`
* retrieve the clean `docker-compose.yml` file [here](https://github.com/NicolasConstant/BirdsiteLive/blob/master/docker-compose.yml)
* change only the following parameters
  * Instance:Domain
  * Instance:AdminEmail
  * Db:Password
  * Twitter:ConsumerKey
  * Twitter:ConsumerSecret
  * POSTGRES_PASSWORD
* validate that `Db:Password` and `POSTGRES_PASSWORD` are the same
* launch the stuff `docker-compose up -d`

it should be working at this point

**Comment by Goelant** [comment]
No it's not :/
But as I was looking for my postgres installation, I didn't found this folder : - ./postgres:/var/lib/postgresql/data for the volumes, it may be linked ? But then why is it working with default password ?

**Comment by Goelant** [comment]
Well now that I swaped docker-compose file to stock one I cant get it to work at all anymore, it must be a problem with docker, i'll try to find out why it cant log to postgres ... Thanks a lot for your help and your time i'll keep you up

**Comment by Goelant** [comment]
OMG I GOT IT TO WORK !

So this is what I did :
- as you said, triple check I am setting only the password, and in the right places
- remove every containers (birdsitelive & birdsitelive_db)
- remove ./postgres
- docker-compose up -d
- get to URL > Gives the above new error
- check the log, see that app is restarting
- wait for it to restart
- access the URL and see that everything is working !


Thanks a lot again, I'm now waiting for twitter to give me elevated accesses and there will be a new birdsitelive instance :D

**Comment by NicolasConstant** [comment]
Glad it work!

> found out I didn't have postgressql installed globaly, but I do not think there were an effect ... In a doubting situation I installed it

You weren't using the postgres docker image?

**Comment by Goelant** [comment]
I was using it but I think I was so desesperate that I tried to find issues in another place ... xD
I'm pretty sure installing postgres aside didn't change anything ahah

**Comment by NicolasConstant** [comment]
It's working, it's the more important. 🙂
