### ISSUE TITLE
Feature request: disable followers only posts

### ISSUE THREAD

**Issue by EXPRESSOG** [NicolasConstant/BirdsiteLive#147]
Hi, I saw that posts made by the bot accounts are followers-only posts and I wanted these posts to be visible to everyone in my instance in the timeline, not only if they are following the account.

Is there already a way to change this and if not can an option be added to disable the followers-only toots?

**Comment by NicolasConstant** [comment]
Hi! 
I understand how useful that could be if you are the admin of your instance, but for every other cases it wouldn't be a good idea:
* it would pollute public timelines with dead content: the aim of BSL is not to flood the Fediverse with Twitter data, just to give a little commodity to get in touch with some accounts that doesn't exists here
* publishing in public would also create public mirrors of personal accounts very easily, that isn't a good thing for many obvious reasons

Still, I do provide an option to make some accounts to publish in Unlisted mode (it's a setting to enable per account), but its aim is only to be used for public figures / brands /etc; and making boost possible.
