### ISSUE TITLE
Purge user from followings

### ISSUE THREAD

**Issue by darkphoenix** [NicolasConstant/BirdsiteLive#161]
My instance appears to have been found by some sort of bot that followed about 10,000 Twitter users it found, uhm, somehow?  I've blocked the bot now, is there any way to neatly purge everything only followed by it?  Also, is there a way (beyond poking the database directly) to get some useful usage stats and possibly purge some Twitter accounts no longer followed by anyone?

**Comment by NicolasConstant** [comment]
If you blacklisted the account it should purge by itself. 
(should, if not, feel free to tell me)

You can have some statistics on the `/statistics` endpoint, you also have an administrator tool available: [BSLManager](https://github.com/NicolasConstant/BirdsiteLive/blob/master/BSLManager.md), I'm not really happy with the state of it, but it's there and it's working (it helps removing abusing accounts, etc).

**Comment by darkphoenix** [comment]
Thanks, it seems it did indeed purge itself and the server capacity thing went down by a lot.  Small side note, any chance of you making an arm64 build of your own Docker image?  I’m currently using rility/birdsitelive, but I’d really rather have an officially maintained image, if it’s not too complicated for you to do.

**Comment by NicolasConstant** [comment]
An Arm64 build would need to set up a CICD pipeline: currently I lazily rely on Docker Hub autobuild that doesn't (at least, it was the case the last time I've checked) support a multi-architecture build. 
But surely would be useful, I just have to find some time to jump back in those kind of setup.
