### ISSUE TITLE
SSL under Docker?

### ISSUE THREAD

**Issue by janngobble** [NicolasConstant/BirdsiteLive#162]
I'm on a Synology - and that's neither here nor there except that means I'm using the docker-compose docker-compose.yml file.
This runs ... i can run the instance and see it, search, and get back a @name@birdsitelive.domain.com (my subdomain) result. BUT the mastodon instance can't reach it 503 due to cert issue (it says).

There's nowhere I can see to add ssl cert info.

Other yml's I've used have something like:
volumes:
            - '~/local-certs:/certs'
            - 'portainer_data:/data'
        command:
            --ssl
            --sslcert /certs/portainer.crt
            --sslkey /certs/portainer.key

What do I need to ensure that BirdsiteLive uses the certs when it get spoken to...and that it can pass the ssl test at: https://www.ssllabs.com/ssltest/  ?

Thanks, Nicolas!

**Comment by prplecake** [comment]
> 1: How often does BSL update posts? And is it something we can control via the yml file?

My understanding was BSL checks for new tweets every 15 minutes, but this get longer the more saturated the BSL instance is.

> 2: BSLmanager: I followed instructions and can see my mastodon ID subscribed to 6 twitter accounts...but I can't figure out how to exit the BSL manager, see how many postings the server has forwarded, etc. Is this on purpose?

Hah! I agree it's not intuitive to close. BSLManager should quid on C-c or C-d, but it does seem to quit on C-q.

**Comment by prplecake** [comment]
The File -> Quit option should work, too!
<img width="157" alt="Screenshot 2022-11-01 at 10 07 46" src="https://user-images.githubusercontent.com/83595468/199266547-8fb0cd79-f76f-45c3-8449-41b4dcf18a83.png">

**Comment by janngobble** [comment]
> The File -> Quit option should work, too!
> <img alt="Screenshot 2022-11-01 at 10 07 46" width="157" src="https://user-images.githubusercontent.com/83595468/199266547-8fb0cd79-f76f-45c3-8449-41b4dcf18a83.png">

Yeah...but nothing I could do would activate this F menu... ssh'd into Synology from macOS.

**Comment by NicolasConstant** [comment]
Yeah BSLManager is a bit buggy and difficult to close, that's something I'd like to revamp entirely.

Happy you've solved your issue!
