### ISSUE TITLE
HTTP Status Code 410 GONE

### ISSUE THREAD

**Issue by KaratekHD** [NicolasConstant/BirdsiteLive#163]
Morning,
I installed Birdsite yesterday.
I followed my own Twitter account and posted something, but it doesn't appear on Mastodon.
8 hours later, I checked `podman logs` and found a bunch of HTTP 410 errors:
![Screenshot_20221104-070720_ConnectBot__01.png](https://user-images.githubusercontent.com/38097062/199904261-91ef1c77-8e9f-4011-a495-9f49c7b3bde4.png)
Could these HTTP 410 errors be what's causing my problem or is it unrelated?
Thank you!
- Jens

**Comment by NicolasConstant** [comment]
They are unrelated, some followers seems to have been blocked by mastodon.social (their account doesn't exists anymore), BSL should purge those accounts automatically.

It take some time to have the synchronization activated, if you posted right after following your account it is possible the system wasn't enabled and didn't see your last tweet, maybe try again?

**Comment by KaratekHD** [comment]
I'm sorry, I completely forgot about this thread. 
My issue is resolved, thank you for your help!
