### ISSUE TITLE
Display options

### ISSUE THREAD

**Issue by mhbManchester** [NicolasConstant/BirdsiteLive#168]
HI, I'm very impressed with Sengi - using the linux version (but also tried it in Firefox).  
It would be good to have an option to choose a light screen version rather than the dark display which appears (unless I've missed it) to be the only option.  Thanks.

**Comment by NicolasConstant** [comment]
Thanks but you're not in the right repo. 😁
Here's the Sengi's one: https://github.com/NicolasConstant/sengi
(also, it's a duplicate, we already have an issue for theme support)
