### ISSUE TITLE
Additional column options

### ISSUE THREAD

**Issue by mhbManchester** [NicolasConstant/BirdsiteLive#169]
It would be really helpful to have an option to add columns for bookmarks (favourites) and users own posts.  I know these are available on the account details via right click on avatar but can't see a way of creating a column to show them.  I'm coming from tweetdeck so that is what I'm used to.
Thanks

**Comment by NicolasConstant** [comment]
Can you reopen this on in the Sengi's repo?
https://github.com/NicolasConstant/sengi
