### ISSUE TITLE
Delete created bot account

### ISSUE THREAD

**Issue by Selduro** [NicolasConstant/BirdsiteLive#170]
Hey,

I've read your thourough explanation on https://write.as/nicolas-constant/closing-the-official-bsl-instance but now I do wonder, if there is any way to delete the created bot account, since I now have an actual account on a mastodon instance using the same handle (because people from twitter know me like that) but the bot and my now real account keep showing up as search results.

regards

**Comment by NicolasConstant** [comment]
Hi!

You could ask to your instance admin to remove / hide the account since it's a local view (not a mastodon dev nor admin, but I guess it's possible).

**Comment by srd424** [comment]
I have a vague feeling there's an activity pub message type to inform of account deletion? If there is and you will have the data and keys from your instance it might be possible (obviously rate limited!)

**Comment by timconsidine** [comment]
> You could ask to your instance admin to remove / hide the account since it's a local view (not a mastodon dev nor admin, but I guess it's possible).

Are there instructions for an admin how to delete an account ?
Or empty the database and start over ?

**Comment by timconsidine** [comment]
For others, this is my hack :

1. connect to the postgres db
`docker exec -it xxxx bash` where xxxx is the container id 
(find container id by `docker ps -a` : name is probably postgres:9.6) 
`psql -h localhost -p 5432 -U birdsitelive` assuming you are using standard settings

2. `delete from twitter_users where acct LIKE 'xxxx'; ` where xxxx is the the name of twitter acct to remove
other tasks : 
`select count(*) from twitter_users;` to show how many on the instance
`delete * from twitter_users` to delete all entries
`select acct from twitter_users where acct = 'xxxx';` to check for a twitter account in the instance

If there is a better way to do this, please share !

**Comment by NicolasConstant** [comment]
This won't really solve this issue: it only remove the account from the local BSL instance DB (and only until someone re-create the bot by following it). 

Currently (0.20.0), blacklisting the bot is the best you can do on your instance (disabling it and blocking recreation of it). But it won't remove remote local copy of it in other instances, so they will always pop-up in search. You can ask your admin to remove those, but that's all you can do. 

But I'm working currently on the next update that will solve this, triggering the proper ActivityPub events / states to disable properly a mirroring account. 🙂

**Comment by timconsidine** [comment]
Thanks for the clarification.
But where is the actual bot operating (taking content from twitter and 'posting') ?
Isn't it on the individual BSL instance ? And doesn't that use the postgres db to know what twitter accounts ?
Is there not a way to stop the bot reposting ?
Appreciate the federation means many instances may know of <twit-acct>@birdsite.xxx.yyy but if the bot is not posting, then that doesn't matter.
Apologies for my ignorance of the process.

**Comment by NicolasConstant** [comment]
There is currently (0.20.0) three ways to stop the bot posting: 
- turn off the instance
- blacklist the account 
- remove the account from the DB

Only the first two prevent the bot to start posting again in all cases: in the third case, anyone following the account again will recreate it and it will start synchronizing data again. 

That being said, this is not really the subject of the issue discussed here that is the presence in the search result of disabled BSL accounts and there is currently no way to handle this. 
And it is important since the biggest issue people have currently with BSL is the search pollution it creates (as it can be misleading for newcomers).

**Comment by timconsidine** [comment]
Thanks for the clarification and good luck with the next phase.

My instance got polluted with many unwanted entries, too many to blacklist manually.
Rightly or wrongly, I deleted them and stuck a http auth on so they can't be recreated (w/o cracking the auth)

**Comment by NicolasConstant** [comment]
handled in 0.21.0
