### ISSUE TITLE
"Search this handle to find it in your instance:" shows wrong domain name.

### ISSUE THREAD

**Issue by maboxx** [NicolasConstant/BirdsiteLive#182]
Hello together,
I think I have successfully created birdsite with Docker. I have a working web page where I can enter e.g. @twittername and the corresponding Twitter account is displayed. 
However, in the field "Search this handle to find it in your instance:" it says @twittername@domain.name.
I think "domain.name" is wrong and my domain name should be displayed there.
What am I doing wrong?

**Comment by maboxx** [comment]
Sorry for my hasty message. I have found the error. I had accidentally deleted "Domain" from "Instance:Domain" in docker-compose.yml :-)

Now everything is displayed correctly. Unfortunately, when I now follow my "bot" in the Tusky app, still no content is displayed.

**Comment by NicolasConstant** [comment]
If the account displayed properly and the follow request succeeded, it will take 15-30 minutes before synchronizing new tweets (only the new ones after that period).

**Comment by maboxx** [comment]
Thank you Nicolas for your answer. It is now synchronized. Does it mean that new tweets are always synced after 15-30 minutes or should it be faster after the initial sync?

**Comment by NicolasConstant** [comment]
BSL synchronize data every 15 mins (on a unsaturated instance), the first one act as an account initialization and therefore takes more time (1st call initialization, 2nd synchronization). 🙂
