### ISSUE TITLE
Remind handle

### ISSUE THREAD

**Issue by Hipska** [NicolasConstant/BirdsiteLive#186]
On the remote_follow page, it would be nice if BSL would remind my handle if I come back to follow another twitter account..

<img width="540" alt="image" src="https://user-images.githubusercontent.com/228588/215527316-28d55800-bfc3-407e-bec7-21d6e24a6ad3.png">

**Comment by NicolasConstant** [comment]
Hi! 
This functionality isn't available in this version of the code, from a quick search it seems it's from the [Pasture fork](https://git.gamers.exposed/pasture/BirdsiteLIVE).

**Comment by Hipska** [comment]
No, it’s a feature request. Didn’t know it existed on a different fork though. Can it be reopened so someone can implement it?

**Comment by NicolasConstant** [comment]
Sorry I didn't develop enough: the `remote_follow` page itself doesn't exist on this version of the code (it's a pasture fork feature), sure it can be added as a feature request but we need it before adding a handle saving/reminder.

**Comment by Hipska** [comment]
Oh, that explains, thanks. Nevermind then..
