### ISSUE TITLE
Resolve twitter short-Urls to the real URLs

### ISSUE THREAD

**Issue by der-On** [NicolasConstant/BirdsiteLive#31]
I would like to have t.co/... links resolved to the correct links without twitter tracking.

Not sure if that is possible, however.

**Comment by NicolasConstant** [comment]
It might be possible: https://developer.twitter.com/en/docs/tco
I'll dig deeper

**Comment by der-On** [comment]
@NicolasConstant Thanks. Can confirm it works, however in mastodons web UI and on fedilab (Android) the resolved links are rendered as plain text. I need to copy paste it.

**Comment by NicolasConstant** [comment]
I just checked in MastoUI and it seems to work fine, can you provide me a tweet that isn't working?
