### ISSUE TITLE
RFE: Add link to twitter profile

### ISSUE THREAD

**Issue by xsuchy** [NicolasConstant/BirdsiteLive#33]
When I subscribe to @michalblaha@beta.birdsite.live and then I click on the avatar, I get info about that account. Which is:

Michal Bláha [Bot]
@michalblaha@beta.birdsite.live 

It would be nice if you can add a link to https://twitter.com/michalblaha

**Comment by NicolasConstant** [comment]
that's something that would add a lot of usability indeed, thanks for your contribution!
