### ISSUE TITLE
RFE resolve @ handlers in profile info box

### ISSUE THREAD

**Issue by xsuchy** [NicolasConstant/BirdsiteLive#34]
The account
  https://twitter.com/michalblaha
Has in info the following string:

  Ředitel @HlidacStatu, propagátor e-gov/chytrého a moderního státu. 

The handler @HlidacStatu is not resolved. It would be nice if can point to https://twitter.com/HlidacStatu

In normal posts, this is resolved correctly. The only missing piece seems to be the account infobox.

**Comment by NicolasConstant** [comment]
yes and if I remember there is also an issue with the links, thanks for pointing that out!
