### ISSUE TITLE
Possible issue with emoji and mentions handling

### ISSUE THREAD

**Issue by mariusor** [NicolasConstant/BirdsiteLive#39]
I might have found two issues with the content handling. See the two posts and the image:

https://beta.birdsite.live/users/quake/statuses/1348283459635081218

https://twitter.com/Quake/status/1348283459635081218

The first issue is with the content that is being forwarded to Mastodon (see how the emoji has been split into two unknown unicode characters)

The second is that @jackyesports user is not converted to a mention.

Both issues might be related to Mastodon, rather than birdsite, because the post looks fine on the later.

![screenshot-20210110193641_396102369-swaygrab](https://user-images.githubusercontent.com/7553/104132052-2b736e00-537b-11eb-97fe-749b2a3f6993.png)

**Comment by NicolasConstant** [comment]
The mention issue is quite surprising, maybe linked with its proximity with the emoji. Thanks for reporting this!
