### ISSUE TITLE
Add link to original tweet

### ISSUE THREAD

**Issue by der-On** [NicolasConstant/BirdsiteLive#40]
In many situations I'd like to look at the original tweet to read comments, or if the tweet was a comment, to read the tweet that was commented. For this it would be nice to have a link to the original tweet.

**Comment by NicolasConstant** [comment]
Yeah I'm not sure how to tackle this one. Adding links in the text content would be very heavy and inelegant, and unless as an option to set on the instance (disabled by default) I wouldn't go down this road. 

From my own usage of the tool, I often open the status (redirection via `instance/users/[username]/status/[id]`) and then click on the tweet to go to Twitter. 
Maybe I should redirect from `instance/users/[username]/status/[id]` to Twitter directly without displaying anything, and that would do the trick.

**Comment by der-On** [comment]
Cool. Thanks. Where can I find the link? It's not appearing in the toots, or is it not deployed yet?

**Comment by NicolasConstant** [comment]
It's the URL of the toot itself. 😉
If you follow it it will redirect you automatically to the original tweet.

**Comment by der-On** [comment]
@NicolasConstant and for that I have to click on the time passed since the toot was posted. Never used that before and just found out. How unlogical is that? Anyway, thanks for implementing it. Helps allot.
