### ISSUE TITLE
Link on retweets

### ISSUE THREAD

**Issue by xsuchy** [NicolasConstant/BirdsiteLive#47]
When user retweet something - and take this as example
  https://twitter.com/michalblaha/status/1349400344627994625
In Mastodon I see:
   https://beta.birdsite.live/users/michalblaha/statuses/1349400344627994625

But I would rather see the whole thread. I.e.,
  https://twitter.com/signalizer/status/1349354616954236929
but it is hard to get this.

At the start of the retweet toot is
  [RT @signalizer]
where @signalize is link to https://beta.birdsite.live/@signalizer (that is fine). I propose to make the "RT" link to tweet with whole thread. I.e., in this specific case to https://twitter.com/signalizer/status/1349354616954236929

**Comment by NicolasConstant** [comment]
Yeah I had the same idea, thanks for documenting it here!

**Comment by NicolasConstant** [comment]
Oh I forgot, you already have a link to the retweeted tweet: it's the `t.co/id` link in the message

**Comment by NicolasConstant** [comment]
fixed in 0.12.1
