### ISSUE TITLE
[Feature Request] Substitute twitter mention with local instance mention

### ISSUE THREAD

**Issue by garritfra** [NicolasConstant/BirdsiteLive#77]
A tweet containing a mention, should redirect to the username on your local birdsite instance.

An example:

```txt
Shoutout to @foobar
```

would be relayed as:

```txt
Shoutout to @foobar@beta.birdsite.live
```

## Considerations

- Does mutating the original tweet generate legal issues?

**Comment by NicolasConstant** [comment]
It's already the case, all mentions are automatically converted to `@mention@instance`. 

But I still have some edge cases not supported by my regex (I'm working on it right now, see #72 ) so maybe you did run into some bugs? 
If you have examples where it's not working, feel free to share them here, I will add them to the unit testing cases.

**Comment by NicolasConstant** [comment]
0.13.0 has new regex that should handle all the use cases.
