### ISSUE TITLE
Enhancement: Flag all BSL twitter accounts as bots

### ISSUE THREAD

**Issue by mostfunkyduck** [NicolasConstant/BirdsiteLive#80]
This project does a really good job of integrating birdsite accounts into the fediverse, but it's so good that they are not immediately obvious as bot accounts.  Even if/when there's equivalent engagement features for this service, it'd be great to be able to know that you're talking to the bird instead of fedi.  Bonus points if it could superimpose the bird onto the profile pic where the bot icon usually goes.

**Comment by NicolasConstant** [comment]
That's a good thing to do indeed... but it's already the case (see Mastodon UI): 
 
![image](https://user-images.githubusercontent.com/5437247/106639197-b72f8300-6552-11eb-9daa-73e5a0454e4c.png)

If you're using a client like [Sengi](https://github.com/NicolasConstant/sengi) is will even display it in the timelines: 

![image](https://user-images.githubusercontent.com/5437247/106639420-f1992000-6552-11eb-82d7-4d3b3d668790.png)

What ActivityPub Server / Client are you using? 

For the icons unfortunately I don't host any data on BSL, I only link to the original stuff, so I won't have a way to edit the icons.

**Comment by mostfunkyduck** [comment]
I meant that it should display on timelines.  Being somewhat new, I had mistakenly thought that bot icons were on the timeline on the web UI.  Oops. I will close this issue.

Also, I will try sengi, that's a necessary feature.

Too bad about the icons, that would be useful :(
